version: '3.1'

services:
  nginx-proxy:
    container_name: nginx-proxy
    image: nginx:alpine
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ca.pem:/etc/nginx/certs/ca.pem
      - ./private.pem:/etc/nginx/certs/private.key
      - ./certificate.pem:/etc/nginx/certs/certificate.pem
    restart: unless-stopped
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external: true
